apiVersion: v1
kind: Service
metadata:
  labels:
    app: lobsters
  name: lobsters-secure
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: lobsters
  type: LoadBalancer
